version: '3.9'


networks:
  polis:
    name: polis
    driver: bridge


services: 
  polis:
    build: "."
    container_name: polis.rest
    restart: on-failure
    networks:
      polis:
        ipv4_address: 10.0.5.1
    expose:
      - 8008
    env_file: environment/container
    command: make production
