# Generated by Django 5.0.6 on 2024-05-29 17:49

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(base.models.ProposalBase, models.Model),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de discussão.', max_length=45, unique=True)),
                ('description', models.TextField(help_text='Descrição do tipo de discussão.')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposer', models.ForeignKey(help_text='Propositor(a).', on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            bases=(base.models.ProposalBase, models.Model),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tema da discussão.', max_length=45, unique=True)),
                ('type', models.ForeignKey(help_text='Tipo de discussão à qual pertence', on_delete=django.db.models.deletion.CASCADE, to='base.type')),
            ],
        ),
    ]
