# Generated by Django 5.0.6 on 2024-06-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='Token de login.', unique=True)),
                ('user', models.ForeignKey(help_text='Usuário qual pertence o token.', on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
